steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull gcr.io/jota-dados-integracao-ga4/paid-media-job:latest || true'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '--cache-from'
      - 'gcr.io/jota-dados-integracao-ga4/paid-media-job:latest'
      - '-t'
      - 'gcr.io/jota-dados-integracao-ga4/paid-media-job:latest'
      - '.'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - jobs
      - update
      - paid-media-job
      - --image=gcr.io/jota-dados-integracao-ga4/paid-media-job:latest
      - --region=southamerica-east1
      - >-
        --set-env-vars=PROJECT_ID=$PROJECT_ID,DATASET_BRONZE=midiapaga_bronze,DATASET_SILVER=midiapaga_silver,DATASET_GA4=ga4_metrics_us,FULL_LOAD=,REPROCESS_DATE=

images:
  - 'gcr.io/jota-dados-integracao-ga4/paid-media-job:latest'

options:
  logging: GCS_ONLY

logsBucket: 'gs://cloud-build-logs-jota-dados-integracao-ga4'
